package com.cnuts.learningexception;

public class HandlingExpWithoutCatch {
public static void main(String[] args) {
	

	
		try {
		int result = 10 + 30;
		System.out.println("Addition result: " + result);
	} finally {
		System.out.println("We can write finally block after try block directly ");
	}
		
		
		

	    }
}
	

	


